export const ADD_PERSON_ACCOUNT_START = 'ADD_PERSON_ACCOUNT_START'
export const ADD_PERSON_ACCOUNT_SUCCESS = 'ADD_PERSON_ACCOUNT_SUCCESS'

export const DELETE_PERSON_ACCOUNT_START = 'DELETE_PERSON_ACCOUNT_START'
export const DELETE_PERSON_ACCOUNT_SUCCESS = 'DELETE_PERSON_ACCOUNT_SUCCESS'
